name: CI

on:
  pull_request:
    branches:
      - main
      - '!dependabot/**'

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # General
  set-condition:
    name: 'Set Condition'
    runs-on: ubuntu-latest
    outputs:
      run_on_pr_and_schedule: ${{ steps.set.outputs.run_on_pr_and_schedule }}
    steps:
      - name: Determine RUN_ON_PR_AND_SCHEDULE
        id: set
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" != "closed" ]] || [[ "${{ github.event_name }}" == "schedule" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "run_on_pr_and_schedule=true" >> $GITHUB_OUTPUT
          else
            echo "run_on_pr_and_schedule=false" >> $GITHUB_OUTPUT
  check_changes:
    name: 'Check Changes'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    needs: set_condition
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      e2e: ${{ steps.filter.outputs.e2e }}
      general: ${{ steps.general.outputs.changed }}
    steps:
      - name: Check for file changes
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            all_ci: &all_ci
              - '.github/workflows/ci.yml'
            frontend: &frontend
              - *all_ci
              - 'apps/frontend/**/package.json'
              - 'apps/frontend/**/package-lock.lock'
              - 'apps/frontend/**/*.js'
              - 'apps/frontend/**/*.ts'
              - 'apps/frontend/**/*.html'
              - 'apps/frontend/**/*.css'
              - 'apps/frontend/**/*.scss'
              - 'apps/frontend/**/*.json'
            e2e: &e2e
              - *all_ci
              - 'apps/qa/**/package.json'
              - 'apps/qa/**/package-lock.lock'
              - 'apps/qa/**/*.ts'
              - 'apps/qa/**/*.json'
            changed:
              - *all_ci
              - *frontend
              - *e2e
      - name: Check if general files have changed
        if: github.event_name == 'pull_request'
        id: general
        run: |
          if [ $(echo '${{ steps.filter.outputs.changed_files }}' | jq .[] | sed '/\(.*Test\.php\)/d' | wc -l ) -eq 0 ]; then
            echo "general=false"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "general=true"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  # Frontend
  frontend_tests:
    name: 'Frontend Tests'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [check_changes]
    if: ${{ needs.set_condition.outputs.run_on_pr_and_schedule == 'true' && needs.check_changes.outputs.general == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Set SHAs for NX
        uses: nrwl/nx-set-shas@v4
      - name: Run Frontend Tests
        run: npm run test --ci
  frontend_build:
    name: 'Frontend Build'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [check_changes]
    if: ${{ needs.set_condition.outputs.run_on_pr_and_schedule == 'true' && needs.check_changes.outputs.general == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Set SHAs for NX
        uses: nrwl/nx-set-shas@v4
      - name: Frontend Build
        run: npm run build:production

  # Linters
  format:
    name: 'Formatting'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [check_changes]
    if: ${{ needs.set_condition.outputs.run_on_pr_and_schedule == 'true' && needs.check_changes.outputs.general == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Set SHAs for NX
        uses: nrwl/nx-set-shas@v4
      - name: Run Formatting
        run: npm run format
  eslint:
    name: 'ESLint'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [check_changes]
    if: ${{ needs.set_condition.outputs.run_on_pr_and_schedule == 'true' && needs.check_changes.outputs.general == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Set SHAs for NX
        uses: nrwl/nx-set-shas@v4
      - name: Run ESLint
        run: npm run eslint
  stylelint:
    name: 'Stylelint'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [check_changes]
    if: ${{ needs.set_condition.outputs.run_on_pr_and_schedule == 'true' && needs.check_changes.outputs.general == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Set SHAs for NX
        uses: nrwl/nx-set-shas@v4
      - name: Run Stylelint
        run: npm run stylelint
