name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Start Nx Cloud distributed execution
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps

      # Prepend with nx-cloud record for Nx Cloud tracking
      - run: npx nx-cloud record -- npx nx affected --target=stylelint --parallel=3
      - run: npx nx-cloud record -- npx nx affected --target=lint --parallel=3
      - run: npx nx-cloud record -- npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx-cloud record -- npx nx affected --target=build --parallel=3
      - run: npx nx-cloud record -- npx nx affected --target=e2e-ci --parallel=1
