name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  setup:
    name: 'Setup and Dependency Caching'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

  format:
    name: 'Code Formatting Check'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Format Check
        run: npx nx format:check

  eslint:
    name: 'ESLint Check'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ESLint Check
        run: npx nx affected --target=lint --base=origin/main --head=HEAD

  stylelint:
    name: 'Stylelint Check'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Stylelint Check
        run: npx nx affected --target=stylelint --base=origin/main --head=HEAD

  test:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: npx nx affected --target=test --base=origin/main --head=HEAD
