name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  setup:
    name: 'Setup Environment'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="test"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

  eslint:
    name: 'Lint with ESLint'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npx nx affected -t lint --base=origin/main --head=HEAD --nx-cloud-distribute

  stylelint:
    name: 'Lint with Stylelint'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npx nx affected -t stylelint --base=origin/main --head=HEAD --nx-cloud-distribute

  format:
    name: 'Check Formatting'
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npx nx format:check --nx-cloud-distribute

  test:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    needs: [setup, eslint, stylelint, format]
    steps:
      - run: npx nx affected -t test --base=origin/main --head=HEAD --nx-cloud-distribute

  e2e:
    name: 'Run E2E Tests'
    runs-on: ubuntu-latest
    needs: [setup, eslint, stylelint, format, test]
    steps:
      - run: npx nx affected -t e2e-ci --base=origin/main --head=HEAD --nx-cloud-distribute

  build:
    name: 'Build Application'
    runs-on: ubuntu-latest
    needs: [setup, eslint, stylelint, format, test, e2e]
    steps:
      - run: npx nx affected -t build --base=origin/main --head=HEAD --nx-cloud-distribute
