name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

jobs:
  eslint:
    name: 'Lint with ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint --base=origin/main --head=HEAD

  stylelint:
    name: 'Lint with Stylelint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t stylelint --base=origin/main --head=HEAD

  format:
    name: 'Check Formatting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx format:check

  test:
    name: 'Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t test --base=origin/main --head=HEAD

  e2e:
    name: 'Run E2E Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t e2e-ci --base=origin/main --head=HEAD

  build:
    name: 'Build Applications'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t build --base=origin/main --head=HEAD --configuration=production
