name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup Environment
    runs-on: ${{ vars.PIPELINE_TESTS_TAG || 'ubuntu-latest' }}
    outputs:
      nx_cache_hit: ${{ steps.cache-nx.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v3
        id: cache-node
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Cache Nx workspace files
        id: cache-nx
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

  changes:
    name: Changes Filter
    runs-on: ${{ vars.PIPELINE_TESTS_TAG || 'ubuntu-latest' }}
    needs: setup
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      e2e: ${{ steps.filter.outputs.e2e }}
      general: ${{ steps.general.outputs.changed }}
    steps:
      - name: Check for file changes 🚗
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            all_ci: &all_ci
              - '.github/workflows/ci.yml'
            frontend: &frontend
              - *all_ci
              - 'apps/frontend/**/package.json'
              - 'apps/frontend/**/package-lock.lock'
              - 'apps/frontend/**/*.js'
              - 'apps/frontend/**/*.ts'
              - 'apps/frontend/**/*.html'
              - 'apps/frontend/**/*.css'
              - 'apps/frontend/**/*.scss'
              - 'apps/frontend/**/*.json'
            e2e: &e2e
              - *all_ci
              - 'apps/qa/**/package.json'
              - 'apps/qa/**/package-lock.lock'
              - 'apps/qa/**/*.ts'
              - 'apps/qa/**/*.json'
            changed:
              - *all_ci
              - *frontend
              - *e2e

  stylelint:
    name: Stylelint
    runs-on: ${{ vars.PIPELINE_TESTS_TAG || 'ubuntu-latest' }}
    needs: [setup, changes]
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - name: Restore Node and Nx Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Run stylelint
        run: npx nx affected -t stylelint

  lint:
    name: Lint
    runs-on: ${{ vars.PIPELINE_TESTS_TAG || 'ubuntu-latest' }}
    needs: [setup, changes]
    if: needs.changes.outputs.frontend == 'true'
    steps:
      - name: Restore Node and Nx Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Run lint
        run: npx nx affected -t lint

  main:
    name: CI
    runs-on: ${{ vars.PIPELINE_TESTS_TAG || 'ubuntu-latest' }}
    timeout-minutes: 30
    needs: [stylelint, lint]
    if: (needs.changes.outputs.general == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch')
    steps:
      - name: Restore Node and Nx Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
            .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: Nx Cloud CI Run
        run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      - uses: nrwl/nx-set-shas@v4
