name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  NX_CI_ACCESS_TOKEN: ${{ secrets.NX_CI_ACCESS_TOKEN }}

permissions:
  actions: read
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      e2e: ${{ steps.filter.outputs.e2e }}
      general: ${{ steps.general.outputs.changed }}
    steps:
      - name: Check for file changes 🚗
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            all_ci: &all_ci
              - '.github/workflows/ci.yml'
            frontend: &frontend
              - *all_ci
              - 'apps/frontend/**/package.json'
              - 'apps/frontend/**/package-lock.lock'
              - 'apps/frontend/**/*.js'
              - 'apps/frontend/**/*.ts'
              - 'apps/frontend/**/*.html'
              - 'apps/frontend/**/*.css'
              - 'apps/frontend/**/*.scss'
              - 'apps/frontend/**/*.json'
            e2e: &e2e
              - *all_ci
              - 'apps/qa/**/package.json'
              - 'apps/qa/**/package-lock.lock'
              - 'apps/qa/**/*.ts'
              - 'apps/qa/**/*.json'
            changed:
              - *all_ci
              - *frontend
              - *e2e
      - name: Check if general files have changed
        if: github.event_name == 'pull_request'
        id: general
        run: |
          if [ $(echo '${{ steps.filter.outputs.changed_files }}' | jq .[] |"frontend\/.*\.spec\.ts\|"frontend\/.*\.po\.ts\|"frontend\/.*\.host\.ts\)/d' | wc -l ) -eq 0 ]; then
            echo "general=false"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "general=true"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: For manual and schedule
        if: (github.event_name == 'pull_request' && github.event.action == 'closed') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_call')
        run: |
          echo "For manual and schedule"

  main:
    name: 'CI'
    runs-on: ${{ vars.PIPELINE_TESTS_TAG }}
    timeout-minutes: 30
    needs: [changes]
    if: (needs.changes.outputs.general == 'true' && github.event_name == 'pull_request' && github.event.action != 'closed') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t stylelint lint
